### ISSUE TITLE
Fixing some gramma

### ISSUE THREAD

**Issue by Zabosee** [wridgeu/wridgeu.github.io#5]
- [x] Page: SAP-Fiori, Question 3: Why is [it] <- missing
- [x] Page: UI5-Folder-Structure: For[e] <- deleting

**Comment by wridgeu** [comment]
Fixed with:

- https://github.com/wridgeu/wridgeu.github.io/wiki/UI5-Folder-Structure/5fcba24677f41846a93fdffaa938bc3a86a3404c
- https://github.com/wridgeu/wridgeu.github.io/wiki/SAP-Fiori/b9fdbc486b036bd3fa8d951731ffb8bf38810369

Appreciate your input.
